import type {
  Child,
  Home,
  Program,
  Campaign,
  Testimonial,
  FAQ,
  ImpactStat,
} from './types'

// Impact Statistics
export const impactStats: ImpactStat[] = [
  {
    label: 'Children Supported',
    value: '2,847',
    description: 'Children receiving care and resources through HavenBridge',
  },
  {
    label: 'Licensed Homes Funded',
    value: '156',
    description: 'Verified foster and transitional homes in our network',
  },
  {
    label: 'Donations Delivered',
    value: '$4.2M',
    description: 'Total funds delivered to children and programs',
  },
  {
    label: 'Programs Sponsored',
    value: '89',
    description: 'Educational, therapeutic, and enrichment programs',
  },
]

// Privacy-Safe Children Profiles
export const children: Child[] = [
  {
    id: 'child-1',
    firstName: 'Marcus',
    initials: 'M.J.',
    ageRange: '10-12',
    region: 'Pacific Northwest',
    image: '/children/child-1.jpg',
    supportSummary: 'Thriving in school, needs support for extracurricular activities and therapy sessions.',
    needs: ['Education Supplies', 'Art Therapy', 'Sports Equipment'],
    goals: ['Join a basketball team', 'Improve reading skills', 'Learn guitar'],
    talents: ['Drawing', 'Math', 'Basketball'],
    votes: 234,
    fundsRaised: 1850,
    fundingGoal: 3000,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u1', date: '2024-03-15', title: 'Academic Progress', content: 'Marcus received an A on his science project!' },
    ],
    relatedPrograms: ['prog-1', 'prog-3'],
    activeCampaigns: ['camp-2'],
  },
  {
    id: 'child-2',
    firstName: 'Lily',
    initials: 'L.R.',
    ageRange: '7-9',
    region: 'Southwest',
    image: '/children/child-2.jpg',
    supportSummary: 'Recently placed in a loving foster home, transitioning well with therapy support.',
    needs: ['Trauma Therapy', 'School Supplies', 'Winter Clothing'],
    goals: ['Feel safe and happy', 'Make new friends', 'Learn to swim'],
    talents: ['Singing', 'Helping others', 'Puzzles'],
    votes: 412,
    fundsRaised: 2200,
    fundingGoal: 2500,
    urgencyLevel: 'high',
    recentUpdates: [
      { id: 'u2', date: '2024-03-18', title: 'Milestone', content: 'Lily made her first friend at her new school!' },
    ],
    relatedPrograms: ['prog-2'],
    activeCampaigns: ['camp-1', 'camp-3'],
  },
  {
    id: 'child-3',
    firstName: 'Daniel',
    initials: 'D.K.',
    ageRange: '14-16',
    region: 'Midwest',
    image: '/children/child-3.jpg',
    supportSummary: 'Preparing for independent living, focused on education and job skills.',
    needs: ['Tutoring', 'Life Skills Training', 'College Prep'],
    goals: ['Graduate high school', 'Get a part-time job', 'Learn to drive'],
    talents: ['Writing', 'Computer skills', 'Leadership'],
    votes: 189,
    fundsRaised: 3100,
    fundingGoal: 5000,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u3', date: '2024-03-10', title: 'Achievement', content: 'Daniel was accepted into a summer coding program!' },
    ],
    relatedPrograms: ['prog-4', 'prog-5'],
    activeCampaigns: ['camp-4'],
  },
  {
    id: 'child-4',
    firstName: 'Sofia',
    initials: 'S.M.',
    ageRange: '4-6',
    region: 'Southeast',
    image: '/children/child-4.jpg',
    supportSummary: 'Young learner with a bright smile, needs early childhood development support.',
    needs: ['Early Learning Materials', 'Speech Therapy', 'Healthy Meals'],
    goals: ['Learn to read', 'Make friends at preschool', 'Express feelings'],
    talents: ['Dancing', 'Imagination', 'Kindness'],
    votes: 567,
    fundsRaised: 1400,
    fundingGoal: 2000,
    urgencyLevel: 'critical',
    recentUpdates: [
      { id: 'u4', date: '2024-03-20', title: 'Progress', content: 'Sofia is now recognizing letters and numbers!' },
    ],
    relatedPrograms: ['prog-1'],
    activeCampaigns: ['camp-1'],
  },
  {
    id: 'child-5',
    firstName: 'Jayden',
    initials: 'J.T.',
    ageRange: '12-14',
    region: 'Northeast',
    image: '/children/child-5.jpg',
    supportSummary: 'Athletic and creative, looking for mentorship and enrichment opportunities.',
    needs: ['Sports Programs', 'Music Lessons', 'Mentorship'],
    goals: ['Try out for soccer team', 'Learn piano', 'Find a mentor'],
    talents: ['Soccer', 'Music', 'Storytelling'],
    votes: 298,
    fundsRaised: 2800,
    fundingGoal: 4000,
    urgencyLevel: 'low',
    recentUpdates: [
      { id: 'u5', date: '2024-03-12', title: 'Achievement', content: 'Jayden scored his first goal in the community league!' },
    ],
    relatedPrograms: ['prog-3', 'prog-5'],
    activeCampaigns: ['camp-2', 'camp-5'],
  },
  {
    id: 'child-6',
    firstName: 'Emma',
    initials: 'E.W.',
    ageRange: '8-10',
    region: 'Mountain West',
    image: '/children/child-6.jpg',
    supportSummary: 'Creative soul who loves art and nature, healing through creative expression.',
    needs: ['Art Supplies', 'Outdoor Programs', 'Counseling'],
    goals: ['Have an art show', 'Go camping', 'Feel confident'],
    talents: ['Painting', 'Nature exploration', 'Poetry'],
    votes: 345,
    fundsRaised: 1600,
    fundingGoal: 2500,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u6', date: '2024-03-14', title: 'Creative Growth', content: 'Emma\'s artwork was displayed at the community center!' },
    ],
    relatedPrograms: ['prog-1', 'prog-3'],
    activeCampaigns: ['camp-3'],
  },
  {
    id: 'child-7',
    firstName: 'Ethan',
    initials: 'E.B.',
    ageRange: '7-9',
    region: 'Pacific Northwest',
    image: '/children/child-7.jpg',
    supportSummary: 'Adventurous spirit who loves exploring and learning new things every day.',
    needs: ['School Supplies', 'Winter Clothing', 'Tutoring'],
    goals: ['Learn to ride a bike', 'Read chapter books', 'Join Cub Scouts'],
    talents: ['Curiosity', 'Building things', 'Telling jokes'],
    votes: 178,
    fundsRaised: 1200,
    fundingGoal: 2500,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u7', date: '2024-03-22', title: 'Milestone', content: 'Ethan finished his first chapter book on his own!' },
    ],
    relatedPrograms: ['prog-1'],
    activeCampaigns: ['camp-2'],
  },
  {
    id: 'child-8',
    firstName: 'Noah',
    initials: 'N.C.',
    ageRange: '2-4',
    region: 'Southeast',
    image: '/children/child-8.jpg',
    supportSummary: 'Energetic toddler full of wonder, needs early development support and a stable home.',
    needs: ['Early Learning Materials', 'Healthy Meals', 'Childcare Support'],
    goals: ['Learn new words', 'Play with other kids', 'Feel safe'],
    talents: ['Running', 'Laughing', 'Exploring'],
    votes: 421,
    fundsRaised: 1800,
    fundingGoal: 2000,
    urgencyLevel: 'high',
    recentUpdates: [
      { id: 'u8', date: '2024-03-19', title: 'Progress', content: 'Noah is learning new words every day and loves storytime!' },
    ],
    relatedPrograms: ['prog-1'],
    activeCampaigns: ['camp-1'],
  },
  {
    id: 'child-9',
    firstName: 'Miguel',
    initials: 'M.R.',
    ageRange: '4-6',
    region: 'Southwest',
    image: '/children/child-9.jpg',
    supportSummary: 'Bright and social boy adjusting to a new home, thrives with structure and encouragement.',
    needs: ['Preschool Supplies', 'Speech Therapy', 'Sports Programs'],
    goals: ['Make friends at school', 'Learn to write his name', 'Play soccer'],
    talents: ['Sharing', 'Building blocks', 'Dancing'],
    votes: 267,
    fundsRaised: 950,
    fundingGoal: 2000,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u9', date: '2024-03-17', title: 'Achievement', content: 'Miguel wrote his first name all by himself!' },
    ],
    relatedPrograms: ['prog-1', 'prog-3'],
    activeCampaigns: ['camp-2'],
  },
  {
    id: 'child-10',
    firstName: 'Kai',
    initials: 'K.L.',
    ageRange: '3-5',
    region: 'Pacific Northwest',
    image: '/children/child-10.jpg',
    supportSummary: 'Resilient little one who loves rain puddles and animals, healing with play therapy.',
    needs: ['Play Therapy', 'Winter Gear', 'Healthy Meals'],
    goals: ['Feel comfortable at daycare', 'Learn colors and shapes', 'Have a pet friend'],
    talents: ['Imagination', 'Animal love', 'Bravery'],
    votes: 389,
    fundsRaised: 1650,
    fundingGoal: 2500,
    urgencyLevel: 'high',
    recentUpdates: [
      { id: 'u10', date: '2024-03-21', title: 'Breakthrough', content: 'Kai had his first full week at daycare without tears!' },
    ],
    relatedPrograms: ['prog-2'],
    activeCampaigns: ['camp-1', 'camp-3'],
  },
  {
    id: 'child-11',
    firstName: 'Liam',
    initials: 'L.P.',
    ageRange: '6-8',
    region: 'Midwest',
    image: '/children/child-11.jpg',
    supportSummary: 'Smart and eager learner in a new school, needs support to catch up academically.',
    needs: ['Tutoring', 'School Supplies', 'After-School Programs'],
    goals: ['Catch up in reading', 'Make the honor roll', 'Join a sports team'],
    talents: ['Math', 'Running', 'Kindness'],
    votes: 312,
    fundsRaised: 2100,
    fundingGoal: 3500,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u11', date: '2024-03-16', title: 'Academic Win', content: 'Liam improved two reading levels this semester!' },
    ],
    relatedPrograms: ['prog-1', 'prog-5'],
    activeCampaigns: ['camp-2'],
  },
  {
    id: 'child-12',
    firstName: 'Oliver',
    initials: 'O.H.',
    ageRange: '4-6',
    region: 'Southeast',
    image: '/children/child-12.jpg',
    supportSummary: 'Gentle and loving boy who bonds deeply with animals, thriving in a nature-based care setting.',
    needs: ['Animal Therapy', 'Outdoor Programs', 'Early Learning'],
    goals: ['Care for animals', 'Start kindergarten', 'Feel confident'],
    talents: ['Animal care', 'Gentleness', 'Outdoor play'],
    votes: 245,
    fundsRaised: 1100,
    fundingGoal: 2000,
    urgencyLevel: 'low',
    recentUpdates: [
      { id: 'u12', date: '2024-03-13', title: 'Connection', content: 'Oliver helped name the new therapy dog at Peaceful Pines!' },
    ],
    relatedPrograms: ['prog-3'],
    activeCampaigns: ['camp-4'],
  },
  {
    id: 'child-13',
    firstName: 'Mason',
    initials: 'M.W.',
    ageRange: '5-7',
    region: 'Northeast',
    image: '/children/child-13.jpg',
    supportSummary: 'Active and imaginative boy who loves climbing and outdoor adventures.',
    needs: ['Sports Equipment', 'Counseling', 'School Supplies'],
    goals: ['Join a climbing club', 'Learn to swim', 'Make lasting friendships'],
    talents: ['Climbing', 'Imagination', 'Energy'],
    votes: 198,
    fundsRaised: 800,
    fundingGoal: 2000,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u13', date: '2024-03-11', title: 'Adventure', content: 'Mason completed his first outdoor obstacle course!' },
    ],
    relatedPrograms: ['prog-3', 'prog-5'],
    activeCampaigns: ['camp-6'],
  },
  {
    id: 'child-14',
    firstName: 'Lucas',
    initials: 'L.D.',
    ageRange: '4-6',
    region: 'Mountain West',
    image: '/children/child-14.jpg',
    supportSummary: 'Curious and joyful boy who lights up every room, needs support for speech development.',
    needs: ['Speech Therapy', 'Early Education', 'Healthy Meals'],
    goals: ['Communicate clearly', 'Start pre-K', 'Make friends'],
    talents: ['Smiling', 'Sharing snacks', 'Dancing'],
    votes: 456,
    fundsRaised: 1900,
    fundingGoal: 2500,
    urgencyLevel: 'high',
    recentUpdates: [
      { id: 'u14', date: '2024-03-20', title: 'Speech Progress', content: 'Lucas said his first full sentence in therapy this week!' },
    ],
    relatedPrograms: ['prog-2'],
    activeCampaigns: ['camp-3'],
  },
  {
    id: 'child-15',
    firstName: 'Jake',
    initials: 'J.R.',
    ageRange: '4-6',
    region: 'Southeast',
    image: '/children/child-15.jpg',
    supportSummary: 'Playful and loyal boy who loves dogs and the outdoors, adjusting to a new foster family.',
    needs: ['Animal Therapy', 'Play Therapy', 'Clothing'],
    goals: ['Bond with foster family', 'Start school confidently', 'Have a pet'],
    talents: ['Animal love', 'Laughter', 'Hugging'],
    votes: 334,
    fundsRaised: 1450,
    fundingGoal: 2500,
    urgencyLevel: 'medium',
    recentUpdates: [
      { id: 'u15', date: '2024-03-18', title: 'Bonding', content: 'Jake is settling in beautifully with his foster family and their golden retriever!' },
    ],
    relatedPrograms: ['prog-2', 'prog-3'],
    activeCampaigns: ['camp-1'],
  },
  {
    id: 'child-16',
    firstName: 'Ryan',
    initials: 'R.M.',
    ageRange: '2-4',
    region: 'Southwest',
    image: '/children/child-16.jpg',
    supportSummary: 'Sweet toddler with a big heart, needs early intervention and a loving stable environment.',
    needs: ['Early Intervention', 'Diapers & Essentials', 'Childcare'],
    goals: ['Hit developmental milestones', 'Feel secure', 'Learn through play'],
    talents: ['Cuddling', 'Stacking blocks', 'Belly laughs'],
    votes: 512,
    fundsRaised: 2400,
    fundingGoal: 3000,
    urgencyLevel: 'critical',
    recentUpdates: [
      { id: 'u16', date: '2024-03-22', title: 'Growth', content: 'Ryan started walking independently this month!' },
    ],
    relatedPrograms: ['prog-1'],
    activeCampaigns: ['camp-1', 'camp-5'],
  },
]

// Licensed Homes
export const homes: Home[] = [
  {
    id: 'home-1',
    name: 'Sunrise Family Home',
    type: 'foster',
    city: 'Portland',
    state: 'OR',
    isVerified: true,
    mission: 'Creating a warm, nurturing environment where every child can heal and grow.',
    description: 'Sunrise Family Home has been providing loving foster care for over 15 years. Our trauma-informed approach ensures every child receives personalized attention and care.',
    services: ['24/7 Care', 'Trauma-Informed Support', 'Educational Assistance', 'Family Therapy'],
    currentNeeds: ['Winter clothing', 'School supplies', 'Therapy funding'],
    childrenSupported: 4,
    capacity: 6,
    donationProgress: 8500,
    donationGoal: 12000,
    votes: 423,
    teamMembers: [
      { name: 'Sarah Johnson', role: 'Lead Caregiver', yearsExperience: 15 },
      { name: 'Michael Johnson', role: 'Support Caregiver', yearsExperience: 12 },
    ],
    licensingInfo: 'Oregon State Licensed Foster Home - License #FH-2019-4521',
    recentUpdates: [
      { id: 'h1u1', date: '2024-03-18', title: 'Home Improvement', content: 'New study room completed for homework and tutoring!' },
    ],
    fundingAllocation: [
      { category: 'Daily Care', percentage: 40 },
      { category: 'Education', percentage: 25 },
      { category: 'Therapy', percentage: 20 },
      { category: 'Activities', percentage: 15 },
    ],
  },
  {
    id: 'home-2',
    name: 'Harbor House',
    type: 'transitional',
    city: 'Seattle',
    state: 'WA',
    isVerified: true,
    mission: 'Preparing young adults for successful independent living through structured support.',
    description: 'Harbor House specializes in helping teens aged 16-21 transition to independent living with life skills training, job placement assistance, and continued education support.',
    services: ['Life Skills Training', 'Job Placement', 'Financial Literacy', 'Counseling'],
    currentNeeds: ['Job training materials', 'Kitchen equipment', 'Computer access'],
    childrenSupported: 8,
    capacity: 10,
    donationProgress: 15200,
    donationGoal: 20000,
    votes: 567,
    teamMembers: [
      { name: 'David Chen', role: 'Program Director', yearsExperience: 10 },
      { name: 'Lisa Park', role: 'Life Coach', yearsExperience: 7 },
    ],
    licensingInfo: 'Washington State Licensed Transitional Housing - License #TH-2020-8834',
    recentUpdates: [
      { id: 'h2u1', date: '2024-03-15', title: 'Success Story', content: 'Two residents secured full-time employment this month!' },
    ],
    fundingAllocation: [
      { category: 'Housing', percentage: 35 },
      { category: 'Life Skills', percentage: 30 },
      { category: 'Education', percentage: 20 },
      { category: 'Emergency Fund', percentage: 15 },
    ],
  },
  {
    id: 'home-3',
    name: 'Meadowbrook Care Home',
    type: 'group',
    city: 'Denver',
    state: 'CO',
    isVerified: true,
    mission: 'Specialized therapeutic care for children with complex needs in a home-like setting.',
    description: 'Meadowbrook provides round-the-clock therapeutic care with on-site counselors, specialized education support, and a calm, structured environment.',
    services: ['Therapeutic Care', 'On-site Counseling', 'Special Education', 'Medical Coordination'],
    currentNeeds: ['Sensory equipment', 'Art therapy supplies', 'Outdoor play equipment'],
    childrenSupported: 12,
    capacity: 14,
    donationProgress: 22000,
    donationGoal: 30000,
    votes: 712,
    teamMembers: [
      { name: 'Dr. Amanda Roberts', role: 'Clinical Director', yearsExperience: 18 },
      { name: 'James Wilson', role: 'House Manager', yearsExperience: 9 },
    ],
    licensingInfo: 'Colorado State Licensed Group Home - License #GH-2018-2234',
    recentUpdates: [
      { id: 'h3u1', date: '2024-03-20', title: 'New Program', content: 'Launched animal-assisted therapy program!' },
    ],
    fundingAllocation: [
      { category: 'Therapeutic Care', percentage: 45 },
      { category: 'Medical', percentage: 25 },
      { category: 'Education', percentage: 20 },
      { category: 'Recreation', percentage: 10 },
    ],
  },
  {
    id: 'home-4',
    name: 'Peaceful Pines Foster Home',
    type: 'foster',
    city: 'Austin',
    state: 'TX',
    isVerified: true,
    mission: 'Every child deserves peace, love, and the chance to discover their potential.',
    description: 'A rural foster home offering children the healing power of nature, animals, and a tight-knit family environment.',
    services: ['Nature-Based Healing', 'Animal Care Programs', 'Tutoring', 'Art Therapy'],
    currentNeeds: ['Animal feed', 'Garden supplies', 'Educational materials'],
    childrenSupported: 3,
    capacity: 4,
    donationProgress: 4200,
    donationGoal: 8000,
    votes: 289,
    teamMembers: [
      { name: 'Maria Garcia', role: 'Lead Caregiver', yearsExperience: 11 },
    ],
    licensingInfo: 'Texas State Licensed Foster Home - License #FH-2021-6678',
    recentUpdates: [
      { id: 'h4u1', date: '2024-03-16', title: 'Spring Garden', content: 'Kids planted their first vegetable garden!' },
    ],
    fundingAllocation: [
      { category: 'Daily Care', percentage: 50 },
      { category: 'Animal Program', percentage: 20 },
      { category: 'Education', percentage: 20 },
      { category: 'Activities', percentage: 10 },
    ],
  },
]

// Programs
export const programs: Program[] = [
  {
    id: 'prog-1',
    name: 'Bright Futures Tutoring',
    type: 'education',
    city: 'Multiple',
    state: 'Nationwide',
    isVerified: true,
    mission: 'Closing the educational gap for children in foster care through personalized learning.',
    description: 'One-on-one and small group tutoring for children of all ages, with special focus on reading, math, and building confidence.',
    services: ['One-on-One Tutoring', 'Homework Help', 'Test Preparation', 'Learning Assessments'],
    currentNeeds: ['Textbooks', 'Tablets', 'Tutor training'],
    childrenSupported: 156,
    donationProgress: 18500,
    donationGoal: 25000,
    votes: 834,
    recentUpdates: [
      { id: 'p1u1', date: '2024-03-19', title: 'Impact', content: 'Students showed 40% improvement in reading scores!' },
    ],
  },
  {
    id: 'prog-2',
    name: 'Healing Hearts Therapy',
    type: 'therapy',
    city: 'Multiple',
    state: 'Nationwide',
    isVerified: true,
    mission: 'Providing trauma-informed mental health support for children healing from adversity.',
    description: 'Licensed therapists offer individual, group, and family therapy sessions tailored to the unique needs of foster children.',
    services: ['Individual Therapy', 'Group Sessions', 'Family Therapy', 'Crisis Support'],
    currentNeeds: ['Therapy materials', 'Telehealth equipment', 'Training funds'],
    childrenSupported: 234,
    donationProgress: 32000,
    donationGoal: 40000,
    votes: 1023,
    recentUpdates: [
      { id: 'p2u1', date: '2024-03-17', title: 'Expansion', content: 'Added telehealth services in 5 new states!' },
    ],
  },
  {
    id: 'prog-3',
    name: 'Creative Expressions',
    type: 'enrichment',
    city: 'Chicago',
    state: 'IL',
    isVerified: true,
    mission: 'Helping children discover their voice through art, music, and creative expression.',
    description: 'Weekly art, music, and drama classes that provide emotional outlets and build confidence and creativity.',
    services: ['Art Classes', 'Music Lessons', 'Drama Club', 'Creative Writing'],
    currentNeeds: ['Art supplies', 'Musical instruments', 'Performance space'],
    childrenSupported: 89,
    donationProgress: 11200,
    donationGoal: 15000,
    votes: 445,
    recentUpdates: [
      { id: 'p3u1', date: '2024-03-14', title: 'Event', content: 'Spring art showcase featured 30 student pieces!' },
    ],
  },
  {
    id: 'prog-4',
    name: 'Ready for Life',
    type: 'life-skills',
    city: 'Phoenix',
    state: 'AZ',
    isVerified: true,
    mission: 'Preparing teens aging out of foster care with essential life skills for independence.',
    description: 'Comprehensive life skills program covering financial literacy, job readiness, cooking, and independent living.',
    services: ['Financial Literacy', 'Job Training', 'Cooking Classes', 'Apartment Living Skills'],
    currentNeeds: ['Training materials', 'Kitchen supplies', 'Job placement partnerships'],
    childrenSupported: 67,
    donationProgress: 9800,
    donationGoal: 18000,
    votes: 378,
    recentUpdates: [
      { id: 'p4u1', date: '2024-03-13', title: 'Achievement', content: '15 graduates secured stable housing this quarter!' },
    ],
  },
  {
    id: 'prog-5',
    name: 'Mentors Matter',
    type: 'mentorship',
    city: 'Multiple',
    state: 'Nationwide',
    isVerified: true,
    mission: 'Connecting foster children with caring adult mentors for lasting relationships.',
    description: 'Trained volunteer mentors provide consistent, positive relationships and guidance to children in foster care.',
    services: ['One-on-One Mentoring', 'Group Activities', 'Career Guidance', 'College Prep'],
    currentNeeds: ['Mentor training', 'Activity funds', 'Background checks'],
    childrenSupported: 312,
    donationProgress: 21500,
    donationGoal: 30000,
    votes: 756,
    recentUpdates: [
      { id: 'p5u1', date: '2024-03-11', title: 'Milestone', content: 'Matched our 500th mentor-mentee pair!' },
    ],
  },
]

// Campaigns
export const campaigns: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Winter Essentials Drive',
    description: 'Providing warm clothing, blankets, and winter necessities to children in foster care before cold weather hits.',
    category: 'essentials',
    goalAmount: 15000,
    amountRaised: 11200,
    supporterCount: 234,
    urgencyLevel: 'high',
    endDate: '2024-04-30',
    beneficiaryType: 'general',
    impactDescription: 'Every $50 provides a complete winter care package for one child.',
    recentUpdates: [
      { id: 'c1u1', date: '2024-03-18', title: 'Progress', content: '180 winter kits delivered so far!' },
    ],
  },
  {
    id: 'camp-2',
    title: 'Back to School Success',
    description: 'Equipping foster children with backpacks, supplies, and technology for a successful school year.',
    category: 'education',
    goalAmount: 25000,
    amountRaised: 18500,
    supporterCount: 412,
    urgencyLevel: 'medium',
    endDate: '2024-08-15',
    beneficiaryType: 'general',
    impactDescription: '$75 provides a complete school supply kit. $200 includes a tablet for homework.',
    recentUpdates: [
      { id: 'c2u1', date: '2024-03-15', title: 'Milestone', content: '250 students equipped for success!' },
    ],
  },
  {
    id: 'camp-3',
    title: 'Therapy Access Fund',
    description: 'Ensuring every child who needs mental health support can access trauma-informed therapy.',
    category: 'therapy',
    goalAmount: 40000,
    amountRaised: 28900,
    supporterCount: 567,
    urgencyLevel: 'critical',
    endDate: '2024-06-30',
    beneficiaryType: 'program',
    beneficiaryId: 'prog-2',
    beneficiaryName: 'Healing Hearts Therapy',
    impactDescription: '$150 covers one month of therapy sessions for a child in need.',
    recentUpdates: [
      { id: 'c3u1', date: '2024-03-20', title: 'Impact', content: '89 children received therapy this month!' },
    ],
  },
  {
    id: 'camp-4',
    title: 'Creative Arts Scholarship',
    description: 'Funding art, music, and drama programs that help children express themselves and build confidence.',
    category: 'enrichment',
    goalAmount: 12000,
    amountRaised: 7800,
    supporterCount: 189,
    urgencyLevel: 'low',
    endDate: '2024-07-31',
    beneficiaryType: 'program',
    beneficiaryId: 'prog-3',
    beneficiaryName: 'Creative Expressions',
    impactDescription: '$100 provides art supplies for 5 children for a month.',
    recentUpdates: [
      { id: 'c4u1', date: '2024-03-12', title: 'Event', content: 'Student art show raised awareness and funds!' },
    ],
  },
  {
    id: 'camp-5',
    title: 'Emergency Housing Support',
    description: 'Providing emergency funding when foster homes face unexpected costs that could disrupt placements.',
    category: 'emergency',
    goalAmount: 30000,
    amountRaised: 19500,
    supporterCount: 345,
    urgencyLevel: 'critical',
    endDate: '2024-12-31',
    beneficiaryType: 'general',
    impactDescription: 'Emergency funds prevent placement disruptions and keep children stable.',
    recentUpdates: [
      { id: 'c5u1', date: '2024-03-19', title: 'Intervention', content: 'Prevented 3 emergency placement changes!' },
    ],
  },
  {
    id: 'camp-6',
    title: 'Home Safety Upgrades',
    description: 'Helping licensed foster homes make necessary safety improvements and accessibility modifications.',
    category: 'home-upgrades',
    goalAmount: 20000,
    amountRaised: 8900,
    supporterCount: 156,
    urgencyLevel: 'medium',
    endDate: '2024-09-30',
    beneficiaryType: 'general',
    impactDescription: '$500 can install safety equipment. $2000 can complete accessibility modifications.',
    recentUpdates: [
      { id: 'c6u1', date: '2024-03-10', title: 'Completed', content: '4 homes received safety upgrades this month!' },
    ],
  },
]

// Testimonials
export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    quote: 'HavenBridge helped us provide the support our foster children needed when we couldn\'t do it alone. The community that rallied around us changed everything.',
    author: 'Sarah & Michael Johnson',
    role: 'Foster Parents',
    location: 'Portland, OR',
  },
  {
    id: 'test-2',
    quote: 'As a program director, I\'ve seen firsthand how donor support transforms children\'s lives. One therapy session can be the turning point a child needs.',
    author: 'Dr. Amanda Roberts',
    role: 'Clinical Director, Meadowbrook Care',
    location: 'Denver, CO',
  },
  {
    id: 'test-3',
    quote: 'I aged out of foster care, and programs like Ready for Life gave me the skills to succeed. Now I mentor other teens through their transition.',
    author: 'Marcus T.',
    role: 'Program Graduate & Mentor',
    location: 'Phoenix, AZ',
  },
]

// FAQs
export const faqs: FAQ[] = [
  {
    id: 'faq-1',
    question: 'How does HavenBridge work?',
    answer: 'HavenBridge connects donors with licensed foster homes, verified programs, and specific support campaigns. Your donations directly fund care, education, therapy, and enrichment for children in foster care. We work only with licensed partners and ensure transparent impact tracking.',
    category: 'general',
  },
  {
    id: 'faq-2',
    question: 'Can I donate without creating an account?',
    answer: 'Yes! You can make one-time donations without an account. However, creating an account allows you to track your impact, vote on community priorities, save causes you care about, and manage recurring donations.',
    category: 'donations',
  },
  {
    id: 'faq-3',
    question: 'Why do I need an account to vote?',
    answer: 'Voting helps our community identify and prioritize urgent needs. Account verification ensures fair voting and prevents abuse. Votes influence which campaigns and homes receive increased visibility, helping direct community attention to the most pressing needs.',
    category: 'voting',
  },
  {
    id: 'faq-4',
    question: 'Why is a payment method required for voting?',
    answer: 'Adding a payment method during signup helps verify your identity and streamlines future support actions. You will NOT be charged automatically. The payment method is stored securely for when you choose to donate.',
    category: 'voting',
  },
  {
    id: 'faq-5',
    question: 'Will I be charged automatically?',
    answer: 'No. Your payment method is stored securely but never charged automatically. You control every donation. Recurring donations require explicit opt-in and can be canceled at any time.',
    category: 'donations',
  },
  {
    id: 'faq-6',
    question: 'Do votes decide where children are placed?',
    answer: 'Absolutely not. Votes only affect visibility and help prioritize support needs within our platform. All placement decisions are made by licensed caseworkers and child welfare professionals. HavenBridge never influences or controls placement decisions.',
    category: 'voting',
  },
  {
    id: 'faq-7',
    question: 'How are homes and programs vetted?',
    answer: 'We only partner with state-licensed foster homes and accredited programs. Our team verifies licensing, conducts background checks, reviews safety protocols, and monitors ongoing compliance. Every partner in our network meets strict child welfare standards.',
    category: 'trust',
  },
  {
    id: 'faq-8',
    question: 'How are donations used?',
    answer: 'Donations fund specific campaigns, programs, or homes you choose. We provide transparent allocation breakdowns for every recipient. Funds cover essentials, education, therapy, enrichment, and emergency support. We maintain minimal overhead to maximize impact.',
    category: 'donations',
  },
  {
    id: 'faq-9',
    question: 'Is child information kept private?',
    answer: 'Yes. We use privacy-safe profiles showing only first names or initials, age ranges, regions, and support needs. No identifying information, photos, or placement details are ever shared publicly. Privacy and safety are our top priorities.',
    category: 'privacy',
  },
  {
    id: 'faq-10',
    question: 'Are donations tax deductible?',
    answer: 'HavenBridge is a registered 501(c)(3) nonprofit organization. All donations are tax-deductible to the extent allowed by law. You will receive a receipt for your records, and annual tax summaries are available in your dashboard.',
    category: 'donations',
  },
]

// Helper functions
export function getChildById(id: string): Child | undefined {
  return children.find(c => c.id === id)
}

export function getHomeById(id: string): Home | undefined {
  return homes.find(h => h.id === id)
}

export function getProgramById(id: string): Program | undefined {
  return programs.find(p => p.id === id)
}

export function getCampaignById(id: string): Campaign | undefined {
  return campaigns.find(c => c.id === id)
}

export function getChildrenByUrgency(level: 'low' | 'medium' | 'high' | 'critical'): Child[] {
  return children.filter(c => c.urgencyLevel === level)
}

export function getCampaignsByCategory(category: string): Campaign[] {
  return campaigns.filter(c => c.category === category)
}

export function getFeaturedCampaigns(count: number = 3): Campaign[] {
  return campaigns
    .sort((a, b) => b.supporterCount - a.supporterCount)
    .slice(0, count)
}

export function getFeaturedHomes(count: number = 3): Home[] {
  return homes
    .sort((a, b) => b.votes - a.votes)
    .slice(0, count)
}

export function getFeaturedPrograms(count: number = 3): Program[] {
  return programs
    .sort((a, b) => b.votes - a.votes)
    .slice(0, count)
}

export function getFeaturedChildren(count: number = 4): Child[] {
  return children
    .sort((a, b) => b.votes - a.votes)
    .slice(0, count)
}
